feat: :sparkles: se agregó mixins de font y line-clamp con sus docume…
CodePartnersTeam/dashboard.foccus.co pull request #39
Opened 2023-12-08 16:37 UTC by Alan-Senderovich

…ntaciones

### Resumen

👉 Se agregaron los mixin de Font y Line-clamp con sus respectivas documentaciones 

### Detalles de los cambios

👉  

### Checklist

👇
- [ ] 

### Referencias

👉 Issue: https://github.com/orgs/CodePartnersTeam/projects/1?pane=issue&itemId=46574925

### Screensshots o documentos

2023-12-08 22:55 UTC, devEstivenValencia requested changes
@Alan-Senderovich por favor revisa estos cambios

2023-12-08 22:55 UTC, devEstivenValencia commented on src/assets/styles/abstracts/_mixins.scss
> +@mixin font($font-size, $color, $font-weight, $line-height, $font-family, $font-style, $font-variant) {
Añade default values a los parámetros

2023-12-08 22:55 UTC, devEstivenValencia commented on src/assets/styles/abstracts/_mixins.scss
> +@mixin line-clamp($-webkit-line-clamp, $-webkit-box-orient: vertical) {
Añade default values a los parámetros

2023-12-08 22:55 UTC, devEstivenValencia commented on src/assets/styles/abstracts/_mixins.scss
> +/// @param {string} $font-variant - The font variant (e.g., normal, small-caps).
Documentacion y comentarios deben estar en español

2023-12-08 22:55 UTC, devEstivenValencia commented on src/assets/styles/abstracts/_mixins.scss
> +/// @param {string} $-webkit-box-orient - The box orientation (e.g., vertical, horizontal).
Documentación y comentarios deben estar en español

2023-12-08 22:57 UTC, devEstivenValencia commented
Te dejo por aca el estandar de trabajo en cuanto al lenguaje https://github.com/CodePartnersTeam/dashboard.foccus.co#-lenguaje

2023-12-11 12:39 UTC, Alan-Senderovich commented on src/assets/styles/abstracts/_mixins.scss
> +@mixin line-clamp($-webkit-line-clamp, $-webkit-box-orient: vertical) {
Con que valores?

2023-12-11 12:39 UTC, Alan-Senderovich commented on src/assets/styles/abstracts/_mixins.scss
> +@mixin font($font-size, $color, $font-weight, $line-height, $font-family, $font-style, $font-variant) {
Con que valores?

2023-12-11 13:05 UTC, devEstivenValencia commented on src/assets/styles/abstracts/_mixins.scss
> +@mixin font($font-size, $color, $font-weight, $line-height, $font-family, $font-style, $font-variant) {
1m, inherit, 400, 1, inherit, normal, normal

2023-12-11 17:03 UTC, devEstivenValencia approved these changes
Aprobado ✅

2023-12-11 17:06 UTC, merged