Sprint 2/fix login service
CodePartnersTeam/dashboard.foccus.co pull request #40
Opened 2023-12-09 17:28 UTC by Diegosapia

### Resumen

👉 

Se creo un interceptor nuevo, este no utiliza autorización comprobando el usuario en local storage, ya que no existía. 

### Detalles de los cambios

👉  
se creo axios.login.ts interceptor para utilizarlo en el login y poder manejar los toast.

### Checklist

👇
- [*] 

### Referencias

👉

### Screensshots o documentos

2023-12-09 23:31 UTC, devEstivenValencia requested changes
No crees un interceptor, maneja la lógica de la petición en el mismo service `try catch`

2023-12-11 14:33 UTC, Diegosapia commented
Estiven, ahi se estan manejando el toas.succes en el form login y la logica en el servicio de login como hablamos recien, esta listo para el pull

2023-12-11 15:04 UTC, devEstivenValencia requested changes
@Diegosapia Revisa lo siguiente

2023-12-11 15:04 UTC, devEstivenValencia commented on src/features/Session/infrastructure/login.service.ts
> +			throw new Error(error.response.message)
> [!NOTE]
> Prueba con un usuario que no este en la base de datos y revisa si la propiedad `error.response.message` es correcto

2023-12-11 17:35 UTC, Diegosapia commented
Ahi se modifico el planteo del condicional en el servicio donde primero se contempla el error y en caso que pase entra al try catch donde se maneja el success o el error correspondiente renderizando el error.response.data.message

2023-12-11 18:01 UTC, devEstivenValencia approved these changes
Aprobado ✅

2023-12-11 18:02 UTC, merged