Sprint 2/changes header
CodePartnersTeam/dashboard.foccus.co pull request #44
Opened 2023-12-14 11:23 UTC by Diegosapia

### Resumen

👉 
modifique el navbar donde se cambio el avatar por el elipses component ( todavia no esta listo pero hay un provisorio ) 
y se agrego el logo de FOCCUS en el mismo.

### Detalles de los cambios

👉  
se agrego el logo de FOCCUS en el header , se eliminaron algunas rutas de navegacion y se agrego sell

### Checklist

👇
solo faltaria implementar el componente Elipses 

- [ ] 

### Referencias

👉

### Screensshots o documentos

2023-12-14 15:34 UTC, devEstivenValencia requested changes

2023-12-14 15:34 UTC, devEstivenValencia commented on src/app/components/Header/Header.navigation.ts
>  export const NAVIGATIONHEADER: any[] = [
No lo dejes `any[]` tipalo correctamente

2023-12-14 16:17 UTC, Diegosapia commented
le cambie el tipado any[] por string[] ahora deberia estar listo para implementar el componente elipses

2023-12-18 16:03 UTC, Diegosapia commented
![Screenshot 2023-12-18 at 17 01 39](https://github.com/CodePartnersTeam/dashboard.foccus.co/assets/81770023/3470d430-a8fa-4561-bca6-8df8c5054bf0)



-----------------------------------                                                                              -----------------------------------------

ahi solucione el problema que estaba presentando el header, se ve que al solucionar el conflicto por alguna razon escribio el nombre de la rama en el html y rompia el estilo.

-----------------------------------                                                                              -----------------------------------------

2023-12-18 16:33 UTC, devEstivenValencia requested changes
@Diegosapia Revisa lo siguiente

2023-12-18 16:33 UTC, devEstivenValencia commented on src/app/components/Header/Header.tsx
> +				{/* <Root>
Elimina todo este comentario

2023-12-18 16:33 UTC, devEstivenValencia commented on src/app/components/Header/userActions.ts
> +		service: async () => await console.log('Intento buscar')
Esto no se va a usar remuevelo

2023-12-18 16:38 UTC, Diegosapia commented on src/app/components/Header/Header.tsx
> +				{/* <Root>
Perfecto, ya lo retire

2023-12-18 16:46 UTC, codepartnersadmin approved these changes
Aprobado ✅

2023-12-18 16:47 UTC, devEstivenValencia approved these changes
Aprobado ✅

2023-12-18 17:44 UTC, merged